// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/condition/publisher.go
//
// Generated by this command:
//
//	mockgen -source=pkg/condition/publisher.go -destination=pkg/condition/mock_publisher.go -package=condition Publisher
//

// Package condition is a generated GoMock package.
package condition

import (
	context "context"
	reflect "reflect"

	types "github.com/amimof/voiyd/api/types/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Report mocks base method.
func (m *MockPublisher) Report(arg0 string, arg1 bool, arg2 *types.ConditionReport) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Report", arg0, arg1, arg2)
}

// Report indicates an expected call of Report.
func (mr *MockPublisherMockRecorder) Report(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockPublisher)(nil).Report), arg0, arg1, arg2)
}

// Run mocks base method.
func (m *MockPublisher) Run(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", arg0)
}

// Run indicates an expected call of Run.
func (mr *MockPublisherMockRecorder) Run(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockPublisher)(nil).Run), arg0)
}

// MockConditionClient is a mock of ConditionClient interface.
type MockConditionClient struct {
	ctrl     *gomock.Controller
	recorder *MockConditionClientMockRecorder
	isgomock struct{}
}

// MockConditionClientMockRecorder is the mock recorder for MockConditionClient.
type MockConditionClientMockRecorder struct {
	mock *MockConditionClient
}

// NewMockConditionClient creates a new mock instance.
func NewMockConditionClient(ctrl *gomock.Controller) *MockConditionClient {
	mock := &MockConditionClient{ctrl: ctrl}
	mock.recorder = &MockConditionClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConditionClient) EXPECT() *MockConditionClientMockRecorder {
	return m.recorder
}

// Condition mocks base method.
func (m *MockConditionClient) Condition(arg0 context.Context, arg1 string, arg2 ...*types.Condition) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Condition", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Condition indicates an expected call of Condition.
func (mr *MockConditionClientMockRecorder) Condition(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Condition", reflect.TypeOf((*MockConditionClient)(nil).Condition), varargs...)
}
