{
 "title": "Blipblop Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(blipblop_build_info,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Rate",
   "type": "timeseries",
   "description": "Total bytes per second across all calls ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(grpc_server_call_rcvd_total_compressed_message_size_bytes_sum{job=\"$job\"}[5m])\n)",
     "legendFormat": "Rcvd"
    },
    {
     "expr": "-sum(\n  rate(grpc_server_call_sent_total_compressed_message_size_bytes_sum{job=\"$job\"}[5m])\n)",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Data Rate (Per Method)",
   "type": "timeseries",
   "description": "Total bytes per second across all calls ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (grpc_method) (\n  rate(grpc_server_call_rcvd_total_compressed_message_size_bytes_sum{job=\"$job\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC requests/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_call_started_total{job=\"$job\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Calls Per Second",
   "type": "timeseries",
   "description": "Call Per second across all methods",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(grpc_server_call_rcvd_total_compressed_message_size_bytes_count{job=\"$job\"}[5m])\n)",
     "legendFormat": "Rcvd"
    },
    {
     "expr": "-sum(\n  rate(grpc_server_call_rcvd_total_compressed_message_size_bytes_count{job=\"$job\"}[5m])\n)",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "Non-OK responses/seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_call_started_total{job=\"$job\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per-Service QPS",
   "type": "timeseries",
   "description": "Requests per second grouped by service/method",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method) (rate(grpc_server_call_started_total{job=\"$job\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "timeseries",
   "description": "All Methods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_call_started_total{job=\"$job\",grpc_code!=\"OK\"}[5m]))  / sum(rate(grpc_server_call_started_total{job=\"$job\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_call_duration_seconds_bucket{job=\"$job\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_call_duration_seconds_bucket{job=\"$job\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "sum(rate(grpc_server_call_duration_seconds_sum{job=\"$job\"}[5m]))\n/\nsum(rate(grpc_server_call_duration_seconds_count{job=\"$job\"}[5m]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Error Percentage per Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (grpc_service,grpc_method) (rate(grpc_server_call_started_total{job=\"$job\",grpc_code!=\"OK\"}[5m]))  / sum by (grpc_service,grpc_method)\n(rate(grpc_server_call_started_total{job=\"$job\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Slow Methods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(\n  5,\n  histogram_quantile(\n    0.95,\n    sum by (le, grpc_service, grpc_method) (\n      rate(grpc_server_call_duration_seconds_bucket{job=\"$job\"}[5m])\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Concurrency",
   "type": "timeseries",
   "description": "Number of Goroutines and Threads total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}",
     "legendFormat": "Goroutines"
    },
    {
     "expr": "go_threads{job=\"$job\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "timeseries",
   "description": "How often GC runs (5m average)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=\"$job\"}[5m])",
     "legendFormat": "5m Avg"
    }
   ]
  },
  {
   "title": "Total CPU seconds per second",
   "type": "timeseries",
   "description": "(Cores used)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Approx. fraction of CPU time spent in GC",
   "type": "timeseries",
   "description": "How often GC runs (5m average)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"$job\"}[5m]) / rate(process_cpu_seconds_total{job=\"$job\"}[5m])",
     "legendFormat": "5m Avg"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", quantile=\"0.25\"}",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"$job\"}[5m]) / rate(go_gc_duration_seconds_count{job=\"$job\"}[5m])",
     "legendFormat": "5m Avg"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Heap Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "timeseries",
   "description": "Resident Memory (MiB)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "up{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Allocations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Objects",
   "type": "timeseries",
   "description": "Heap Pressure Proxy",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{job=\"$job\",code!=\"200\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}