{
 "title": "voiyd Server",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(voiyd_build_info,job)"
    }
   },
   { "name": "DATASOURCE", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Concurrency",
   "type": "timeseries",
   "description": "Number of Goroutines and Threads total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}",
     "legendFormat": "Goroutines"
    },
    {
     "expr": "go_threads{job=\"$job\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "timeseries",
   "description": "How often GC runs (5m average)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=\"$job\"}[5m])",
     "legendFormat": "5m Avg"
    }
   ]
  },
  {
   "title": "Total CPU seconds per second",
   "type": "timeseries",
   "description": "(Cores used)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Approx. fraction of CPU time spent in GC",
   "type": "timeseries",
   "description": "How often GC runs (5m average)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"$job\"}[5m]) / rate(process_cpu_seconds_total{job=\"$job\"}[5m])",
     "legendFormat": "5m Avg"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", quantile=\"0.25\"}",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"$job\"}[5m]) / rate(go_gc_duration_seconds_count{job=\"$job\"}[5m])",
     "legendFormat": "5m Avg"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Heap Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "timeseries",
   "description": "Resident Memory (MiB)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "up{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Allocations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Objects",
   "type": "timeseries",
   "description": "Heap Pressure Proxy",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{job=\"$job\",code!=\"200\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}