syntax = "proto3";

package services.leases.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "types/v1/meta.proto";

option go_package = "github.com/amimof/voiyd/api/services/leases/v1;leases";

service LeaseService {
  rpc Get(GetRequest) returns (GetResponse) {
    option (google.api.http) = {get: "/api/v1/leases/{uid}"};
  }
  rpc List(ListRequest) returns (ListResponse) {
    option (google.api.http) = {get: "/api/v1/leases"};
  }
  rpc Acquire(AcquireRequest) returns (AcquireResponse) {
    option (google.api.http) = {
      post: "/api/v1/leases"
      body: "*"
    };
  }
  rpc Release(ReleaseRequest) returns (ReleaseResponse) {
    option (google.api.http) = {delete: "/api/v1/leases/{id}"};
  }
  rpc Revoke(RevokeRequest) returns (RevokeResponse);
  rpc Renew(RenewRequest) returns (RenewResponse) {
    option (google.api.http) = {
      put: "/api/v1/leases/{task_id}"
      additional_bindings: {patch: "/api/v1/leases/{task_id}"}
    };
  }
}

// Lease represents a node's right to run a task
message Lease {
  string version = 1;
  types.v1.Meta meta = 2 [(buf.validate.field).required = true];
  LeaseConfig config = 3 [(buf.validate.field).required = true];
  LeaseStatus status = 4;
}

message LeaseConfig {
  string task_id = 1 [(buf.validate.field).string.uuid = true];
  string node_id = 2 [(buf.validate.field).string.uuid = true];
  google.protobuf.Timestamp acquired_at = 3;
  google.protobuf.Timestamp renew_time = 4;
  google.protobuf.Timestamp expires_at = 5;
  uint32 ttl_seconds = 6;
  uint64 fencing_token = 7;
}

message LeaseStatus {
  string token_hash = 1;
}

message AcquireRequest {
  string task_id = 1 [(buf.validate.field).string.uuid = true];
  string node_id = 2 [(buf.validate.field).string.uuid = true];
}

message AcquireResponse {
  Lease lease = 1;
  string token = 2;
  uint64 fencing_token = 3;
}

message RenewRequest {
  string task_id = 1 [(buf.validate.field).string.uuid = true];
  string node_id = 2 [(buf.validate.field).string.uuid = true];
  string token = 3;
}

message RenewResponse {
  Lease lease = 1;
  string token = 2;
  uint64 fencing_token = 3;
}

message ReleaseRequest {
  string id = 1;
  string task_id = 2 [(buf.validate.field).string.uuid = true];
  string node_id = 3 [(buf.validate.field).string.uuid = true];
  string token = 4;
}

message ReleaseResponse {
  bool released = 1;
}

message RevokeRequest {
  string id = 1;
  string task_id = 2 [(buf.validate.field).string.uuid = true];
  string node_id = 3 [(buf.validate.field).string.uuid = true];
}

message RevokeResponse {
  bool released = 1;
}

message GetRequest {
  string uid = 1 [(buf.validate.field).string.uuid = true];
}

message GetResponse {
  Lease lease = 1;
}

message ListRequest {
  int32 limit = 1;
  map<string, string> selector = 2;
  bool expired_only = 3;
}

message ListResponse {
  repeated Lease leases = 1;
}
