syntax = "proto3";

package services.containersets.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";
import "services/tasks/v1/tasks.proto";
import "types/v1/meta.proto";

option go_package = "github.com/amimof/voiyd/api/services/containersets/v1;containersets";

service ContainerSetService {
  rpc Get(GetRequest) returns (GetResponse) {
    option (google.api.http) = {
      get: "/api/v1/containersets/{uid}"
      additional_bindings: {get: "/api/v1/containersets/{name}"}
    };
  }
  rpc List(ListRequest) returns (ListResponse) {
    option (google.api.http) = {get: "/api/v1/containersets"};
  }
  rpc Create(CreateRequest) returns (CreateResponse) {
    option (google.api.http) = {
      post: "/api/v1/containerssets"
      body: "containerSet"
    };
  }
  rpc Update(UpdateRequest) returns (UpdateResponse) {
    option (google.api.http) = {
      put: "/api/v1/containersets/{uid}"
      body: "containerSet"
      additional_bindings: {
        put: "/api/v1/containersets/{name}"
        body: "containerSet"
      }
    };
  }
  rpc Delete(DeleteRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/api/v1/containersets/{uid}"
      additional_bindings: {delete: "/api/v1/containersets/{name}"}
    };
  }
}

message ContainerSet {
  string version = 1 [
    (buf.validate.field).string.min_len = 4,
    (buf.validate.field).string.pattern = "^[a-z0-9]+(?:[._-][a-z0-9]+)*/[a-z0-9]+(?:[._-][a-z0-9]+)*$",
    (buf.validate.field).required = true
  ];
  types.v1.Meta meta = 2 [(buf.validate.field).required = true];
  services.tasks.v1.Config template = 3 [(buf.validate.field).required = true];
}

message GetRequest {
  option (buf.validate.message).oneof = {
    fields: [
      "uid",
      "name"
    ]
  };
  string uid = 1 [(buf.validate.field).string.min_len = 1];
  string name = 2 [(buf.validate.field).string.min_len = 1];
}

message GetResponse {
  ContainerSet containerSet = 1;
}

message CreateRequest {
  ContainerSet containerSet = 1 [(buf.validate.field).required = true];
}

message CreateResponse {
  ContainerSet containerSet = 1;
}

message UpdateRequest {
  option (buf.validate.message).oneof = {
    fields: [
      "uid",
      "name"
    ]
  };
  string uid = 1 [(buf.validate.field).string.min_len = 1];
  string name = 2 [(buf.validate.field).string.min_len = 1];
  ContainerSet containerSet = 3;
  google.protobuf.FieldMask update_mask = 4;
}

message UpdateResponse {
  ContainerSet containerSet = 1;
}

message DeleteRequest {
  option (buf.validate.message).oneof = {
    fields: [
      "uid",
      "name"
    ]
  };
  string uid = 1 [(buf.validate.field).string.min_len = 1];
  string name = 2 [(buf.validate.field).string.min_len = 1];
}

message ListRequest {
  uint32 limit = 1;
  map<string, string> selector = 2;
}

message ListResponse {
  repeated ContainerSet containerSets = 1;
}
