// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/services/logs/v1/logs.proto

package logs

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LogRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LogRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LogRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LogRequestMultiError, or
// nil if none found.
func (m *LogRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LogRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContainerId

	if len(errors) > 0 {
		return LogRequestMultiError(errors)
	}

	return nil
}

// LogRequestMultiError is an error wrapping multiple validation errors
// returned by LogRequest.ValidateAll() if the designated constraints aren't met.
type LogRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogRequestMultiError) AllErrors() []error { return m }

// LogRequestValidationError is the validation error returned by
// LogRequest.Validate if the designated constraints aren't met.
type LogRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogRequestValidationError) ErrorName() string { return "LogRequestValidationError" }

// Error satisfies the builtin error interface
func (e LogRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogRequestValidationError{}

// Validate checks the field values on LogResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LogResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LogResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LogResponseMultiError, or
// nil if none found.
func (m *LogResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *LogResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LogLine

	// no validation rules for Timestamp

	if len(errors) > 0 {
		return LogResponseMultiError(errors)
	}

	return nil
}

// LogResponseMultiError is an error wrapping multiple validation errors
// returned by LogResponse.ValidateAll() if the designated constraints aren't met.
type LogResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogResponseMultiError) AllErrors() []error { return m }

// LogResponseValidationError is the validation error returned by
// LogResponse.Validate if the designated constraints aren't met.
type LogResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogResponseValidationError) ErrorName() string { return "LogResponseValidationError" }

// Error satisfies the builtin error interface
func (e LogResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogResponseValidationError{}
