// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: services/logs/v1/logs.proto

package logs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogServiceClient interface {
	TailLogs(ctx context.Context, in *TailLogRequest, opts ...grpc.CallOption) (LogService_TailLogsClient, error)
	PushLogs(ctx context.Context, opts ...grpc.CallOption) (LogService_PushLogsClient, error)
}

type logServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServiceClient(cc grpc.ClientConnInterface) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) TailLogs(ctx context.Context, in *TailLogRequest, opts ...grpc.CallOption) (LogService_TailLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LogService_ServiceDesc.Streams[0], "/services.logs.v1.LogService/TailLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &logServiceTailLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LogService_TailLogsClient interface {
	Recv() (*LogEntry, error)
	grpc.ClientStream
}

type logServiceTailLogsClient struct {
	grpc.ClientStream
}

func (x *logServiceTailLogsClient) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *logServiceClient) PushLogs(ctx context.Context, opts ...grpc.CallOption) (LogService_PushLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LogService_ServiceDesc.Streams[1], "/services.logs.v1.LogService/PushLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &logServicePushLogsClient{stream}
	return x, nil
}

type LogService_PushLogsClient interface {
	Send(*LogEntry) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type logServicePushLogsClient struct {
	grpc.ClientStream
}

func (x *logServicePushLogsClient) Send(m *LogEntry) error {
	return x.ClientStream.SendMsg(m)
}

func (x *logServicePushLogsClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LogServiceServer is the server API for LogService service.
// All implementations must embed UnimplementedLogServiceServer
// for forward compatibility
type LogServiceServer interface {
	TailLogs(*TailLogRequest, LogService_TailLogsServer) error
	PushLogs(LogService_PushLogsServer) error
	mustEmbedUnimplementedLogServiceServer()
}

// UnimplementedLogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLogServiceServer struct {
}

func (UnimplementedLogServiceServer) TailLogs(*TailLogRequest, LogService_TailLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method TailLogs not implemented")
}
func (UnimplementedLogServiceServer) PushLogs(LogService_PushLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method PushLogs not implemented")
}
func (UnimplementedLogServiceServer) mustEmbedUnimplementedLogServiceServer() {}

// UnsafeLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServiceServer will
// result in compilation errors.
type UnsafeLogServiceServer interface {
	mustEmbedUnimplementedLogServiceServer()
}

func RegisterLogServiceServer(s grpc.ServiceRegistrar, srv LogServiceServer) {
	s.RegisterService(&LogService_ServiceDesc, srv)
}

func _LogService_TailLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TailLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogServiceServer).TailLogs(m, &logServiceTailLogsServer{stream})
}

type LogService_TailLogsServer interface {
	Send(*LogEntry) error
	grpc.ServerStream
}

type logServiceTailLogsServer struct {
	grpc.ServerStream
}

func (x *logServiceTailLogsServer) Send(m *LogEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _LogService_PushLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogServiceServer).PushLogs(&logServicePushLogsServer{stream})
}

type LogService_PushLogsServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*LogEntry, error)
	grpc.ServerStream
}

type logServicePushLogsServer struct {
	grpc.ServerStream
}

func (x *logServicePushLogsServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *logServicePushLogsServer) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LogService_ServiceDesc is the grpc.ServiceDesc for LogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.logs.v1.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TailLogs",
			Handler:       _LogService_TailLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PushLogs",
			Handler:       _LogService_PushLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "services/logs/v1/logs.proto",
}
